services:
  mongodb:
    image: mongo:8
    container_name: shorten_url_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: shorten_url
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
