name: server pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    defaults:
      run:
        working-directory: server
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      SHUFFLE_SECRET: ${{ secrets.SHUFFLE_SECRET }}

    services:
      mongodb:
        image: mongo:8
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: shorten_url
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
